name: Deploy to Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build, Archive, Upload
    runs-on: ubuntu-24.04
    timeout-minutes: 10 # Archi can stall on errors
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: repository
    - name: Prepare Archi Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: Archi-550-CoArchi-094
        path: |
          archi.tgz
          coarchi.archiplugin
    - name: Download Archi
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose --output-document='archi.tgz' 'https://www.archimatetool.com/downloads/archi/5.5.0/Archi-Linux64-5.5.0.tgz'
        wget --no-verbose --output-document='coarchi.archiplugin' 'https://www.archimatetool.com/downloads/coarchi/coArchi_0.9.4.archiplugin'
    - name: Verify Archi
      run: |
        echo '4451e3613e17c8a6fe806d8c4599087eb756973f archi.tgz' | sha1sum --check
        echo '43bc8fc67f6ac503682570885a0c56dc69f5b328 coarchi.archiplugin' | sha1sum --check
    - name: Update cache
      if: steps.restore-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: Archi-550-CoArchi-094
        path: |
          archi.tgz
          coarchi.archiplugin
    - name: Install Archi
      run: |
        tar xf archi.tgz
        # install plugin according to https://www.archimatetool.com/plugins/
        mkdir --parents "$HOME/.archi/dropins"
        unzip coarchi.archiplugin -d "$HOME/.archi/dropins"
    - name: Generate HTML
      run: |
        # use xvfb-run to get a virtual framebuffer and run headless
        # https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface/8e7baff522421fb744ae921c46e4be178df7fdc3#running-on-linux-without-graphics-headless
        xvfb-run ./Archi/Archi -application com.archimatetool.commandline.app -consoleLog -nosplash --abortOnException --modelrepository.loadModel "$PWD/repository" --html.createReport html_report
    - name: Prepare HTML for Pages
      run: |
        # fix permissions, see
        # https://github.com/actions/upload-pages-artifact#example-permissions-fix-for-linux
        chmod -v -R +rX "html_report" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

        # now pack it for export, in required format
        # https://github.com/actions/upload-pages-artifact#artifact-validation
        mv html_report _site
        tar czf github-pages _site
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1 

  deploy:
    name: Deploy
    needs: build
    
    permissions:
      actions: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.pages_url }}

    runs-on: ubuntu-24.04
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
